dist: xenial
language: cpp
compiler: clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++-9 cmake doxygen graphviz -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60
before_script:
  - cd HW3
  - ls
  - gcc --version
  - g++ --version
  - cmake --version
script:
  - doxygen doc/doxyfile
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - ls
  - cd doc
  - ls
  - cd html
  - ls
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhamstergamer:$BINTRAY_API_KEY "https://api.bintray.com/content/hamstergamer/otus_cpp/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    on:
      branch: master

  - provider: pages
    skip_cleanup: true
    local-dir: $TRAVIS_BUILD_DIR/HW3/doc/html
    github-token: $GITHUB_TOKEN
    on:
      branch: master