dist: xenial
language: cpp
compiler: clang
before_script:
  - git init
  - git submodule init
  - git submodule add https://github.com/google/googletest.git
  - git submodule update --init --recursive
  - cd HW2
  - sudo apt-get install libgtest-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhamstergamer:$BINTRAY_API_KEY "https://api.bintray.com/content/hamstergamer/otus_cpp/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
