dist: xenial
language: cpp
compiler: clang
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install g++-9 cmake doxygen graphviz -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 60
before_script:
  - cd HW4
  - ls
  - gcc --version
  - g++ --version
  - cmake --version
script:
  - doxygen doc/Doxyfile
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -f -T Editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhamstergamer:$BINTRAY_API_KEY "https://api.bintray.com/content/hamstergamer/otus_cpp/Editor/$TRAVIS_BUILD_NUMBER/Editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

  - provider: pages
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/HW4/doc/html
    github_token: $GITHUB_TOKEN
    on:
      branch: master